Pin flate2 dependency for pixel bridge to be lower than 1.1.10.
The png and exr crate depend on miniz_oxide v0.8 while flate2 depend on the API incompatible v0.9. Since the cargo files are flattened during the build
we get an error when building pixel bridge:

```
error: duplicate key
Error:   --> ../../build/cargo/rust_9a010/x86_64-unknown-linux-gnu/debug/deps/rust-a593f8c403d61387/Cargo.toml:36:1
   |
36 | miniz_oxide = "0.9.1"
   | ^^^^^^^^^^^
Error: Cargo build of bindings failed
```
PiperOrigin-RevId: 973821953